function definirModulo(slug: string) {
  return {
    Visualizar: `${slug}.visualizar`,
    Editar: `${slug}.editar`,
    Aprovar: `${slug}.aprovar`,
    Configurar: `${slug}.configurar`,
  } as const;
}

export const Permissoes = {
  Dashboard: definirModulo('dashboard'),
  Unidades: definirModulo('unidades'),
  Cnpjs: definirModulo('cnpjs'),
  Fornecedores: definirModulo('fornecedores'),
  Usuarios: definirModulo('usuarios'),
  Colaboradores: definirModulo('colaboradores'),
  Clientes: definirModulo('clientes'),
  Produtos: definirModulo('produtos'),
  CategoriasProduto: definirModulo('categorias-produto'),
  UnidadesMedida: definirModulo('unidades-medida'),
  TabelasPreco: definirModulo('tabelas-preco'),
  Estoque: definirModulo('estoque'),
  PedidosVenda: definirModulo('pedidos-venda'),
  Aprovacoes: definirModulo('aprovacoes'),
  Notificacoes: definirModulo('notificacoes'),
  FormasPagamentoConfig: definirModulo('formas-pagamento-config'),
  Financeiro: definirModulo('financeiro'),
  Orcamentos: definirModulo('orcamentos'),
  Pdv: definirModulo('pdv'),
  Compras: definirModulo('compras'),
  DevolucoesVenda: definirModulo('devolucoes-venda'),
  Expedicao: definirModulo('expedicao'),
  Fiscal: definirModulo('fiscal'),
  Contratos: definirModulo('contratos'),
  Producao: definirModulo('producao'),
  Rastreabilidade: definirModulo('rastreabilidade'),
  Relatorios: definirModulo('relatorios'),
  Manutencao: definirModulo('manutencao'),
  Logistica: definirModulo('logistica'),
  Crm: definirModulo('crm'),
  CobrancaCredito: definirModulo('cobranca-credito'),
  MetasVendedor: definirModulo('metas-vendedor'),
  Representantes: definirModulo('representantes'),
  RegrasComissao: definirModulo('regras-comissao'),
  PermissoesGranulares: definirModulo('permissoes-granulares'),
  Auditoria: definirModulo('auditoria'),
} as const;
